# environment-languages.yml
name: languages_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - rust
  - pip:
      # --- Key Language/Merge Frameworks ---
      - torch==2.7.1
      - transformers==4.52.4
      - accelerate==1.3.0
      - peft==0.17.1
      - mergekit==0.0.6
      - deepspeed==0.17.1
      - importlib-metadata
      - attrdict

      # --- Other Dependencies for Language Eval ---
      - datasets==3.6.0
      - fire
      - sympy
      - pandas
      - numpy
      - scipy
      - sentencepiece
      - tokenizers
      - pyyaml
      - tqdm